mqtt:
  enabled: true
  host: homeassistant.1fern.com
  topic_prefix: frigate
  user: frigate
  password: o-06IoJ\X1=X

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30

snapshots:
  enabled: true

objects:
  track:
    - person
    - cat
    - dog
    - bear
    - backpack
    - bicycle
    - car
    - umbrella
    - handbag
    - suitcase
    - potted plant

review:
  alerts:
    labels:
      - person
      - cat
      - dog
      - bear
  detections:
    labels:
      - car
      - person
      - cat
      - dog
      - bear

go2rtc:
  streams:
    camera_1:
      - rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=0
    camera_2:
      - rtsp://admin:g2Wa0nD70P9v@10.1.1.231:554/cam/realmonitor?channel=1&subtype=0

cameras:
  camera_1:
    detect:
      width: 1056
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      danger_zone:
        coordinates: 0.358,0.189,0.347,0.802,0.336,1,1,1,1,0
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
    review:
      alerts:
        required_zones: danger_zone
  camera_2:
    detect:
      width: 1056
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.231:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.231:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      danger_zone:
        coordinates: 0.467,0,0.338,0.115,0,0.244,0,0.805,0.778,0.867,0.742,0
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
    review:
      alerts:
        required_zones: danger_zone

version: 0.14
