mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True

snapshots:
  enabled: True

cameras:
  camera_1:
    detect:
      width: 1056
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

version: 0.14
