mqtt:
  enabled: true
  host: homeassistant.1fern.com
  topic_prefix: frigate
  user: frigate
  password: o-06IoJ\X1=X

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30

snapshots:
  enabled: true

objects:
  track:
    - person
    - cat
    - dog
    - bear
    - backpack
    - bicycle
    - car
    - umbrella
    - handbag
    - suitcase
    - potted plant

review:
  alerts:
    labels:
      - person
      - cat
      - dog
      - bear
  detections:
    labels:
      - car
      - person
      - cat
      - dog
      - bear

go2rtc:
  streams:
    camera_1:
      - rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=0
    camera_2:
      - rtsp://admin:g2Wa0nD70P9v@10.1.1.231:554/cam/realmonitor?channel=1&subtype=0

cameras:
  camera_1:
    detect:
      width: 1056
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.230:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      danger_zone:
        coordinates: 0,0.697,0,1,1,1,1,0.717,0.874,0.725,0.779,0.959,0.555,0.944,0.553,0.717
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
      sidewalk_road:
        coordinates: 
          0,0.484,0,0.704,0.56,0.738,0.565,0.954,0.784,0.954,1,0.724,1,0.605,0.402,0.631,0.214,0.556
        loitering_time: 0
        objects:
          - bicycle
          - car
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones: danger_zone
  camera_2:
    detect:
      width: 1056
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.231:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:g2Wa0nD70P9v@10.1.1.231:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      danger_zone:
        coordinates: 
          0.226,0.48,0.189,0.3,0.058,0.296,0.102,0,0,0,0,1,0.198,1,0.296,1,0.551,1,1,0.995,1,0.662,0.74,0.637,0.74,0.574,0.578,0.545
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
          - bear
          - bicycle
          - potted plant
    review:
      alerts:
        required_zones: danger_zone

version: 0.14
